spring.application.name=api-brindes
# ── CONFIGURAÇÃO DO BANCO DE DADOS MYSQL ──
# ── CONFIGURAÇÃO DO HIBERNATE / JPA ──
# Atualiza o banco automaticamente sem apagar seus dados
spring.jpa.hibernate.ddl-auto=update
# Exibe os comandos SQL no console para você acompanhar o que o Spring está fazendo
spring.jpa.show-sql=true
# Formata o SQL no console para ficar mais legível
spring.jpa.properties.hibernate.format_sql=true
# Se a nuvem fornecer as credenciais, o Java usa elas. Se não, usa as suas locais (para você continuar testando no seu PC).
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/estoque_brindes?createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:leo3434}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Forcando o Render a reiniciar o servidor